import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Layout/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl' className='bg-mainBg'>
      <head>
        <link rel='shortcut icon' href='./favicon.svg' type='image/x-icon' />
      </head>
      <body>
        <div className='w-full h-[100vh] flex flex-col'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
