import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

import ClientProviderLayout from "./components/Layout/ClientProviderLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl' className='bg-mainBg'>
      <head>
        <link rel='shortcut icon' href='./favicon.svg' type='image/x-icon' />
      </head>
      <body>
        <NextTopLoader color='#768ebc' />
        <ClientProviderLayout>{children}</ClientProviderLayout>
      </body>
    </html>
  );
}
